### ISSUE TITLE
Implement a jsonpath assertion

### ISSUE THREAD

**Issue by theredfish** [owlduty/grillon#25]
A common need when testing json bodies is to create jsonpath assertions. We currently support two assertions `is` and `is_not` that can be used with the `json_body` function. For example `json_body(is(r#"{"a":"b"}"#))`.

Now for testing a subpart of the json we could implement the following assertion : `json_body(jsonpath(selector, expected))`. Let's take this json data as an example (based on [jsonpath_rust doc](https://docs.rs/jsonpath-rust/latest/jsonpath_rust/)) :

```json
 {
  "shop": {
   "orders": [
      {"id": 1, "active": true},
      {"id": 2 },
      {"id": 3 },
      {"id": 4, "active": true}
    ]
  }
}
```
The selector to find all the orders by `id` with the field `active` is : `$.shop.orders[?(@.active)].id`. The result is `[1,4]`. Based on this example, our assertion would be : `json_body(jsonpath("$.shop.orders[?(@.active)].id", vec![1,4]))`.

To support this feature we can use a Rust library. We have several candidates :

- [jsonpath_rust](https://crates.io/crates/jsonpath-rust)
- [jsonpath](https://crates.io/crates/jsonpath)
- [jsonpath_lib](https://crates.io/crates/jsonpath_lib)

## List of tasks

- [x] Add assertion is
- [x] Add assertion is_not
- [ ] #40
- [ ] Add assertion contains
- [ ] Add relevant doc in the book

**Comment by theredfish** [comment]
# Grillon API

We need to support a range of different `Predicate` for json path while we keep the functional paradigm. As a starting point we can support `is`, `is_not`, `contains`, `does_not_contain`. Then depending on the complexity (essentially because of type casting), we can consider to add in the same pull request `is_less_than`, `between` and add a new assertion `is_more_than`.

If we want to follow the functional programming paradigm we already have, the library should offer one of the following formats:

1. `json_path("$.shop.orders[?(@.active)]", is([1,4]))`
2. or `json_path("$.shop.orders[?(@.active)]".is([1,4]))`

The first solution seems a bit more idiomatic and naturally tends to separate the selector from the expected value. The second solution might be easier to implement since we don't have to add a new abstraction layer for accepting more than one parameter.

For 1. we need to consider a new `Expression` structure, following the same idea as `Range` but where we can have a left hand that is always a literal or a `String`, the right hand that is an `Expression`.

I'm still considering something like:

`json_body(json_path("$.shop.orders[?(@.active)]", is([1,4])))` but we are losing a bit in readability. But at the same time it makes a lot of sense to keep body related features in the same assertion function. The implementation might however be complex due to the current design of an `Expression<T>` - should be explored during the implementation.

_Note: `json_body` will certainly be renamed to `body` once the API is better defined for manipulating several protocols and reponse bodies_

_Note bis: Later we will add a `Xpath` capability to explore a body._

# Type manipulation

As we are testing values for a given json path, we manipulate json data. Which means the Rust type conversion can be fairly complex: What is  the type of a number represented by a string ? Should we convert the number or the string into the expected value? I see different cases where a `Value` can be compared to a concrete type such as `Value::Number(Number::PosInt(1))` can be compared to `1` thanks to the implementation of `PartialEq`:

```rust
enum N {
    PosInt(u64),
    /// Always less than zero.
    NegInt(i64),
    /// Always finite.
    Float(f64),
}

impl PartialEq for N {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (N::PosInt(a), N::PosInt(b)) => a == b,
            (N::NegInt(a), N::NegInt(b)) => a == b,
            (N::Float(a), N::Float(b)) => a == b,
            _ => false,
        }
    }
}
```

During the development phase and the library choice this should be kept in mind. 

# Lib choice
[jsonpath_lib](https://crates.io/crates/jsonpath_lib) seems to be the most reliable library at the moment with +3 millions of downloads with popular [dependents libraries](https://crates.io/crates/jsonpath_lib/reverse_dependencies). However the choice will mainly depend on:

- The ease of integration with Grillon (return type, error management, flexibility)
- Correctness

For the latter it's difficult to evaluate without a standard test suite just like for [json schema](https://github.com/json-schema-org/JSON-Schema-Test-Suite/) (also mentioned in #9 ). There was an ongoing project to test the Rust json path libraries with @yds12 - might be worth revisiting at some point. But it shouldn't prevent the API design.

As we are following the adapter design pattern it shouldn't be hard to change the underlying library without breaking the API.

**Comment by theredfish** [comment]
I have a first working version but I'm not satisfied with the API, it's way too verbose and difficult to organize code correctly. Here is an example: 

```rust
#[tokio::test]
async fn json_path_should_not_be_equal() {
    let var_name = HttpMockServer::new();
    let mock_server = var_name;
    mock_server.get_valid_user();

    Grillon::new(mock_server.server.url("/").as_ref())
        .unwrap()
        .get("users/1")
        .assert()
        .await
        .json_body(json_path(
            "$".to_string(),
            is(json!([{
                "id": 2,
                "name": "Max",
            }])),
        ));
}
```

Separation of concerns is always a good thing as it makes things easier to read and maintain. I think the following code example would be better:

```rust
#[tokio::test]
async fn json_path_should_not_be_equal() {
    let var_name = HttpMockServer::new();
    let mock_server = var_name;
    mock_server.get_valid_user();

    Grillon::new(mock_server.server.url("/").as_ref())
        .unwrap()
        .get("users/1")
        .assert()
        .await
        .json_path(
            "$".to_string(),
            is(json!(
            [{
                "id": 2,
                "name": "Max",
            }])),
        );
}
```

- I'm not a fan of always passing an array of json objects - I will see if I can automatically wrap json into array if it's missing. 
- `"$".to_string()` should ideally replaced by an `&str`
- after a first successful implementation, support more types for `json_path` predicate expression argument: `&str`, `String`. Should follow the same idea as the http body dsl

**Comment by yds12** [comment]
A possibility for the `json_path` function to avoid the `"$".to_string()` is to accept a `T: AsRef<str>`. This can be `String` or `&str`, then you can call `as_ref()` inside the function to get a `&str` (then if you want a `String`, you can call `to_owned` on it). But since you probably do want a `String`, this wouldn't be great because if the user pass an owned `String`, you would get a ref from it and then convert it back to `String`. In this case maybe a `T: Into<Cow<'a, str>>` would be better. This is implemented by `String` and also by `&str`. Then inside the function you can call `into_owned` to get a `String` (this way, if the user pass a `String`, this operation is cheap, it's just getting the string from the `Cow` enum, but if it's a `&str` it will clone, however since you need a `String`, when the user pass a `&str` a clone is inevitable anyways).

Maybe the same idea could be used for some other types (like JSON): by using some trait bounds like `T: Into<Json>` where Json is a type that you can use to wrap `serde_json::Value`; then the user can pass a `Value` or a `String`, or `&str`.

**Comment by theredfish** [comment]
Thanks @yds12 I'll explore your different propositions - seems what the library needs to factorize the uses 👍

**Comment by theredfish** [comment]
[jsonpath_rust](https://crates.io/crates/jsonpath-rust) is finally the lib I decided to pursue with. After some tests, I prefer the API to  [jsonpath_lib](https://crates.io/crates/jsonpath_lib) and the repository is active. There are a bunch of bugs that need to be fixed but I can also contribute all along and help here and there.
